Make api retries more robust again (#826)
Ideally API retries should apply when:
(a) we are not even able to reach the server to perform a request AND
(b) when the server returns an error response

We originally were doing both, but in 0.29.0 stopped doing (b) (see
[this
commit](https://github.com/sematic-ai/sematic/commit/fd60736f890f7fea6316a647a83920891265c45e)).
This PR restores us to do both.

Testing
-------
Injected this into `PUT /api/v1/graph`:
```
if random.random() < 0.5:
    raise ValueError("Random error!")
```
and submitted the `add` pipeline, made sure it still ran through to
successful completion.

To ensure we didn't regress on the issue addressed by #684, performed
the following tests:

(1) turned the local server off and submitted the add pipeline example.
Confirmed that the submission eventually failed (after 6 tries) with:

```
sematic.api_client.APIConnectionError: Unable to connect to the Sematic API at http://localhost:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
```

(2) turned the server on and submitted the add example. Midway through,
used ctrl+c and confirmed that the pipeline stopped executing
immediately and all incomplete runs were marked as failed/canceled.