Fix apparent uncancelable infinite reconnect loop when Server is unreachable (#684)
Fixes #293.

When a pipeline is submitted when the Server is not reachable, the
apparent effect is an infinite reconnect loop:
```
~/work/sematic$ bazel run sematic/examples/testing_pipeline:__main___local
[...]
INFO:__main__:Invoking the pipeline...
INFO:sematic.resolvers.state_machine_resolver:Starting resolution 6e81ce12fce14954be2235f144d54e0a
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 1 seconds...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>, retrying in 10 seconds...
```

This is because each call to the Server has retries around it, and it
actually begins with another prerequisite call of checking the Server
version, which also has retries.

The above snippet also contains cancelation events, sent via `Ctrl^C` in
the CLI (lines beginning with `^C`).
This actually makes the problem worse, as the cancelation workflow
itself tries to connect to the Server with retries as well, and each of
which themselves perform the retriable Server version check.

The result is a snowball effect of a very large number of total calls,
with sleeps between them. The pipeline submission can only be canceled
by sending a kill signal to the process from another terminal.

New users that have attempted to set up their environments have hit this
issue and have been disheartened by the bad experience. The workaround
of canceling it from another terminal is also not immediately obvious to
most new users.

This PR makes the prerequisite version check not perform retries, as its
encompassing call is retried anyway, and makes the pipeline submission
workflow cancelable by removing retries from the cancelation signal
workflow.

The recent switch from `eventlet` to `gevent` has changed the behavior
of the server on new connections. Retries had to be extended to the
`socket.io` clients as well.

## Testing

Tested in the cloud and locally.

No cancelation example:
```
~/work/sematic$ time bazel run sematic/examples/testing_pipeline:__main___local
[...]
INFO:__main__:Invoking the pipeline...
INFO:sematic.resolvers.state_machine_resolver:Starting resolution de4a6a9b9cc74108902c3af5d24aa19b
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying _get in 1 seconds with 3 tries left...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying _get in 2.1 seconds with 2 tries left...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying _get in 4.3 seconds with 1 tries left...
ERROR:sematic.resolvers.state_machine_resolver:Unable to fail resolution: Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/examples/testing_pipeline/__main__.py", line 398, in <module>
    main()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/examples/testing_pipeline/__main__.py", line 393, in main
    result = future.resolve(resolver)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/future.py", line 44, in resolve
    self.value = resolver.resolve(self)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/state_machine_resolver.py", line 50, in resolve
    self._resolution_loop()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/state_machine_resolver.py", line 75, in _resolution_loop
    self._resolution_will_start()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/local_resolver.py", line 224, in _resolution_will_start
    self._sio_client.connect(get_config().socket_io_url, namespaces=["/pipeline"])
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/pip_dependencies3_8_python_socketio/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1679095575.9924748 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x147a24190>: Failed to establish a new connection: [Errno 61] Connection refused'))

real	0m12.092s
user	0m4.070s
sys	0m2.478s
~/work/sematic$
```

Cancelation example:
```
~/work/sematic$ time bazel run sematic/examples/testing_pipeline:__main___local
[...]
INFO:__main__:Invoking the pipeline...
INFO:sematic.resolvers.state_machine_resolver:Starting resolution 05dedad8a192415cbebc9fdcaa0c6025
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying _get in 1 seconds with 3 tries left...
^CWARNING:sematic.resolvers.state_machine_resolver:Received signal 2; canceling resolution...
ERROR:sematic.resolvers.state_machine_resolver:Unable to fail resolution: Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
	$ sematic settings set SEMATIC_API_ADDRESS <address>
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/examples/testing_pipeline/__main__.py", line 398, in <module>
    main()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/examples/testing_pipeline/__main__.py", line 393, in main
    result = future.resolve(resolver)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/future.py", line 44, in resolve
    self.value = resolver.resolve(self)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/state_machine_resolver.py", line 50, in resolve
    self._resolution_loop()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/state_machine_resolver.py", line 75, in _resolution_loop
    self._resolution_will_start()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/sematic/sematic/resolvers/local_resolver.py", line 224, in _resolution_will_start
    self._sio_client.connect(get_config().socket_io_url, namespaces=["/pipeline"])
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/testing_pipeline/__main___local.runfiles/pip_dependencies3_8_python_socketio/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1679095734.2099771 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1691ef820>: Failed to establish a new connection: [Errno 61] Connection refused'))

real	0m5.302s
user	0m3.968s
sys	0m2.465s
~/work/sematic$
```