Fix malformed API client error message (#774)
Fixes an issue where the API Client logs a malformed error message:
```
sematic.api_client.ServerError: The Sematic server could not handle the POST request to http://127.0.0.1:5001/api/v1/resolutions/44fe6d5a6a9743fc86206ce13091fb62/schedule. NonePlease check the Sematic server logs for more information.
```

The problem is here: `[...]/schedule. NonePlease check the [...]`

After fixing the error message format:
```
sematic.api_client.ServerError: The Sematic server could not handle the POST request to http://127.0.0.1:5001/api/v1/resolutions/2c8d8da0322644689064cda9390bef5c/schedule. Please check the Sematic Server logs for more information.
```

And after fixing this particular endpoint's error handling:
```
sematic.api_client.BadRequestError: The POST request to http://127.0.0.1:5001/api/v1/resolutions/0b2bc556d6174e79ab8d2c96ab7d0d8f/schedule was invalid, response was 400. The Server provided the following error message:

Missing setting:

Set it with:

    $ sematic server-settings set KUBERNETES_NAMESPACE VALUE

Please check the Sematic Server logs for more information.
```

All endpoints need to be audited and their error handling fixed, but
this is out of scope for this fix.