Create EE image and EE wheel-extras (#524)
We want to make it so that people using EE features have access to the
relevant code, but people who are not using it do not require the extra
dependencies. This PR makes that possible. You can now `pip install
sematic` for a "normal" pip install, `pip install sematic[ray]` for the
Ray integrations, and `pip install sematic[all]` for *all* extra
integrations. For the server, we produce just 2 editions: the standard
one (that we have always produced) and an ee one, which has used `pip
install sematic[all]` and has all extras.

Testing
-------
Deployed a server image that had installed `sematic[all]`, and then
executed:
`bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud
--detach --ray-resource`, giving [this
run](https://dev1.dev-usw2-sematic0.sematic.cloud/pipelines/sematic.examples.testing_pipeline.pipeline.testing_pipeline/6353ebe6ed51467e8738bafb49fd485c#run=c274256db56e448bbfef7d0fed74ecca&tab=logs)

```
$ make wheel
$ cp bazel-bin/sematic/sematic-0.22.2-py3-none-any.whl ~/tmp/
$ cd ~/tmp
$ virtualenv --python=$(which python3.9) ~/venvs/test_wheel
$ source ~/venvs/test_wheel/bin/activate
$ pip install sematic-0.22.2-py3-none-any.whl
$ python3 -c "import sematic; print('Hi')"
Hi
$ python3 -c "import ray"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ray'
$ python3 -c "from sematic.ee.ray import SimpleRayCluster"
Traceback (most recent call last):
  File "/Users/josh/venvs/test_wheel/lib/python3.9/site-packages/sematic/ee/ray.py", line 6, in <module>
    from sematic.ee.plugins.external_resource.ray.cluster import (  # noqa: F401,E402
  File "/Users/josh/venvs/test_wheel/lib/python3.9/site-packages/sematic/ee/plugins/external_resource/ray/cluster.py", line 9, in <module>
    import ray  # type: ignore
ModuleNotFoundError: No module named 'ray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/josh/venvs/test_wheel/lib/python3.9/site-packages/sematic/ee/ray.py", line 20, in <module>
    raise ImportError(
ImportError: This import requires Sematic to be installed with `pip install sematic[ray]`
$ pip install sematic-0.22.2-py3-none-any.whl[ray]
$ python3 -c "import ray; print('hi')"
hi
$ python3 -c "from sematic.ee.ray import SimpleRayCluster; print('hi')"
hi
$ deactivate
$ make release-server TAG=testing
$ docker run -it --entrypoint=python3 sematic/sematic-server:testing -c "import sematic; print('Hi')"
Hi
$ docker run -it --entrypoint=python3 sematic/sematic-server:testing -c "from sematic.ee.ray import SimpleRayCluster; print('Hi')" 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sematic/ee/ray.py", line 6, in <module>
    from sematic.ee.plugins.external_resource.ray.cluster import (  # noqa: F401,E402
  File "/usr/local/lib/python3.9/site-packages/sematic/ee/plugins/external_resource/ray/cluster.py", line 9, in <module>
    import ray  # type: ignore
ModuleNotFoundError: No module named 'ray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/sematic/ee/ray.py", line 20, in <module>
    raise ImportError(
ImportError: This import requires Sematic to be installed with `pip install sematic[ray]`
$ docker run -it --entrypoint=python3 sematic/sematic-server-ee:testing -c "from sematic.ee.ray import SimpleRayCluster; print('Hi')"
Hi
```

---------

Co-authored-by: Josh Bauer <josh@sematic.dev>