Fix PyYaml dependency errors (#1057)
All Bazel commands started failing with this error:
```
$ bazel run sematic/cli:main -- version
INFO: Repository pip_dependencies3_8_pyyaml instantiated at:
  /Users/tudorscurtu/work/sematic/WORKSPACE:130:16: in <toplevel>
  /private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/pip_dependencies3_8/requirements.bzl:56:20: in install_deps
Repository rule whl_library defined at:
  /private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/rules_python/python/pip_install/pip_repository.bzl:574:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_dependencies3_8_pyyaml':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/rules_python/python/pip_install/pip_repository.bzl", line 550, column 13, in _whl_library_impl
		fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library pip_dependencies3_8_pyyaml failed: Collecting pyyaml==6.0
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
 (  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/pypi__pip/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/pypi__pip/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/pypi__pip/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 548, in run
          self.add_defaults()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/pip-build-env-17apk0l3/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]


[repeats several times]


note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/python3_8_aarch64-apple-darwin/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/python3_8_aarch64-apple-darwin/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 105, in <module>
    main()
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 81, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/python3_8_aarch64-apple-darwin/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/external/python3_8_aarch64-apple-darwin/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '-r', '/var/folders/1y/ct207mxn2857y9rlv15g6jzc0000gn/T/tmpqz143dwi']' returned non-zero exit status 1.
)
ERROR: Analysis of target '//sematic/cli:main' failed; build aborted:
INFO: Elapsed time: 4.894s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (173 packages loaded, 37321 targets configured)
ERROR: Build failed. Not running target
```

This seems to be caused when trying to source the PyYaml 6.0 dependency,
which [does not seem to have any
issues](https://pypi.org/project/PyYAML/6.0/), and has been used for 2
years.

Switching to the new version 6.0.1 seems to fix the issue.